### ISSUE TITLE
False Check for message

### ISSUE THREAD

**Issue by xopham** [ntolazzi/xkcd-matrix-bot#2]
in line 33 you check:
`if not event['content']['msgtype'] == 'm.text':`
you can avoid the try-except if you use something like:
`if event['type'] == 'm.room.message':`
this ensures that you are working with a message in a room and not an invite or something

**Comment by ntolazzi** [comment]
Thanks for the comment, I'm not sure whether I agree because in Python it is generally advised to use  EAFP (easier to ask for forgiveness than permission) pattern. See [here](https://docs.quantifiedcode.com/python-anti-patterns/readability/asking_for_permission_instead_of_forgiveness_when_working_with_files.html).
